export default [
  {
    "name": "곽빈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "47",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68220",
    "birthday": "1999-05-28",
    "body": "187cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "김동주",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "4",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51230",
    "birthday": "2002-02-14",
    "body": "190cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김정우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "16",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68830",
    "birthday": "1999-05-15",
    "body": "183cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "김택연",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "63",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54263",
    "birthday": "2005-06-03",
    "body": "181cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "박신지",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "49",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68249",
    "birthday": "1999-07-16",
    "body": "185cm, 75kg",
    "handedness": "우투우타"
  },
  {
    "name": "박치국",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "1",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67266",
    "birthday": "1998-03-10",
    "body": "177cm, 78kg",
    "handedness": "우언우타"
  },
  {
    "name": "벤자민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 33,
    "jerseyNumber": "48",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52043",
    "birthday": "1993-07-26",
    "body": "188cm, 95kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이병헌",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 23,
    "jerseyNumber": "29",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52204",
    "birthday": "2003-06-04",
    "body": "183cm, 95kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이영하",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "50",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66291",
    "birthday": "1997-11-01",
    "body": "192cm, 91kg",
    "handedness": "우투우타"
  },
  {
    "name": "이용찬",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "45",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "77211",
    "birthday": "1989-01-02",
    "body": "185cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "잭로그",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 30,
    "jerseyNumber": "39",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55239",
    "birthday": "1996-04-23",
    "body": "183cm, 84kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "최민석",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "68",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55268",
    "birthday": "2006-07-02",
    "body": "188cm, 84kg",
    "handedness": "우투우타"
  },
  {
    "name": "최승용",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "28",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51264",
    "birthday": "2001-05-11",
    "body": "190cm, 87kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김기연",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "22",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66112",
    "birthday": "1997-09-07",
    "body": "178cm, 106kg",
    "handedness": "우투우타"
  },
  {
    "name": "양의지",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 39,
    "jerseyNumber": "25",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "76232",
    "birthday": "1987-06-05",
    "body": "180cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "윤준호",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "27",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53296",
    "birthday": "2000-11-14",
    "body": "179cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "박성재",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "5",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51298",
    "birthday": "2002-11-18",
    "body": "186cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "박준순",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "52",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55252",
    "birthday": "2006-07-13",
    "body": "180cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "박지훈",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "37",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50204",
    "birthday": "2000-09-07",
    "body": "183cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "박찬호",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "7",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64646",
    "birthday": "1995-06-05",
    "body": "178cm, 72kg",
    "handedness": "우투우타"
  },
  {
    "name": "안재석",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "62",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51203",
    "birthday": "2002-02-15",
    "body": "185cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이유찬",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "13",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67207",
    "birthday": "1998-08-05",
    "body": "175cm, 68kg",
    "handedness": "우투우타"
  },
  {
    "name": "김민석",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "2",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53554",
    "birthday": "2004-05-09",
    "body": "185cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김인태",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 32,
    "jerseyNumber": "33",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63257",
    "birthday": "1994-07-03",
    "body": "178cm, 78kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "류승민",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 22,
    "jerseyNumber": "14",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53404",
    "birthday": "2004-10-11",
    "body": "185cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "전다민",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "9",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54214",
    "birthday": "2001-08-21",
    "body": "177cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "정수빈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 36,
    "jerseyNumber": "31",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "79231",
    "birthday": "1990-10-07",
    "body": "175cm, 70kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "조수행",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "51",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66209",
    "birthday": "1993-08-30",
    "body": "178cm, 73kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김영현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "20",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51097",
    "birthday": "2002-08-18",
    "body": "177cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "김호준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 28,
    "jerseyNumber": "56",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68269",
    "birthday": "1998-05-17",
    "body": "180cm, 82kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박웅",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "57",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50205",
    "birthday": "1997-11-12",
    "body": "192cm, 103kg",
    "handedness": "우투우타"
  },
  {
    "name": "박정수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "17",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "65639",
    "birthday": "1996-01-29",
    "body": "178cm, 74kg",
    "handedness": "우언좌타"
  },
  {
    "name": "안치호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 22,
    "jerseyNumber": "120",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56220",
    "birthday": "2004-11-30",
    "body": "191cm, 101kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이기석",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "123",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53202",
    "birthday": "2002-06-07",
    "body": "181cm, 80kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이주엽",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "43",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50262",
    "birthday": "2001-03-26",
    "body": "188cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "최주형",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "15",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56215",
    "birthday": "2006-08-19",
    "body": "174cm, 70kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "류현준",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "67",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54219",
    "birthday": "2005-03-25",
    "body": "182cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "이희성",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "121",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56221",
    "birthday": "2004-02-02",
    "body": "179cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "장규빈",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "44",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50244",
    "birthday": "2001-04-21",
    "body": "186cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "김동준",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "11",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52267",
    "birthday": "2002-09-04",
    "body": "193cm, 100kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김민혁",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "10",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "65269",
    "birthday": "1996-05-03",
    "body": "188cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "남태웅",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "118",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56208",
    "birthday": "2007-01-08",
    "body": "175cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "신민철",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "103",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52294",
    "birthday": "2003-01-13",
    "body": "185cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "심건보",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "117",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56217",
    "birthday": "2003-11-17",
    "body": "183cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "양석환",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 35,
    "jerseyNumber": "53",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64153",
    "birthday": "1991-07-15",
    "body": "185cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "이종혁",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "126",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56226",
    "birthday": "2000-02-22",
    "body": "183cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "임서준",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "125",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53293",
    "birthday": "2004-07-11",
    "body": "185cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "임종성",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "3",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54236",
    "birthday": "2005-03-03",
    "body": "183cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김대한",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "32",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69238",
    "birthday": "2000-12-06",
    "body": "185cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "김주오",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "66",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56266",
    "birthday": "2007-09-14",
    "body": "178cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "손아섭",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 38,
    "jerseyNumber": "8",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "77532",
    "birthday": "1988-03-18",
    "body": "174cm, 84kg",
    "handedness": "우투좌타"
  },
  {
    "name": "임현철",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "116",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56216",
    "birthday": "2007-10-21",
    "body": "180cm, 70kg",
    "handedness": "우투좌타"
  },
  {
    "name": "천현재",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "58",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52208",
    "birthday": "1999-07-05",
    "body": "183cm, 90kg",
    "handedness": "우투좌타"
  }
];
