export default [
  {
    "name": "강재민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "55",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50705",
    "birthday": "1997-04-03",
    "body": "180cm, 89kg",
    "handedness": "우언우타"
  },
  {
    "name": "류현진",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 39,
    "jerseyNumber": "99",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "76715",
    "birthday": "1987-03-25",
    "body": "190cm, 113kg",
    "handedness": "좌투우타"
  },
  {
    "name": "박상원",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "58",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67703",
    "birthday": "1994-09-09",
    "body": "187cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "박준영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "96",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52731",
    "birthday": "2003-03-02",
    "body": "190cm, 103kg",
    "handedness": "우투우타"
  },
  {
    "name": "박준영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "68",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56709",
    "birthday": "2002-06-03",
    "body": "184cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "에르난데스",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "12",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56712",
    "birthday": "1999-04-13",
    "body": "190cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "왕옌청",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "19",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56719",
    "birthday": "2001-02-14",
    "body": "180cm, 82kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이민우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "27",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65616",
    "birthday": "1993-02-09",
    "body": "185cm, 104kg",
    "handedness": "우투우타"
  },
  {
    "name": "이상규",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "18",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65117",
    "birthday": "1996-10-20",
    "body": "185cm, 77kg",
    "handedness": "우투우타"
  },
  {
    "name": "장유호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "28",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69645",
    "birthday": "2000-05-25",
    "body": "179cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "정우주",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "61",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55743",
    "birthday": "2006-11-07",
    "body": "184cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "조동욱",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 22,
    "jerseyNumber": "57",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54768",
    "birthday": "2004-11-02",
    "body": "190cm, 82kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "화이트",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "24",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56724",
    "birthday": "1999-08-09",
    "body": "190cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "황준서",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 21,
    "jerseyNumber": "29",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54729",
    "birthday": "2005-08-22",
    "body": "185cm, 78kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "최재훈",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "13",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "78288",
    "birthday": "1989-08-27",
    "body": "178cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "허인서",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "59",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52764",
    "birthday": "2003-07-11",
    "body": "182cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "강백호",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "50",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68050",
    "birthday": "1999-07-29",
    "body": "184cm, 98kg",
    "handedness": "우투좌타"
  },
  {
    "name": "노시환",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "8",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69737",
    "birthday": "2000-12-03",
    "body": "185cm, 105kg",
    "handedness": "우투우타"
  },
  {
    "name": "박정현",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "63",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50709",
    "birthday": "2001-07-27",
    "body": "183cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "심우준",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "7",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64006",
    "birthday": "1995-04-28",
    "body": "183cm, 75kg",
    "handedness": "우투우타"
  },
  {
    "name": "이도윤",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "5",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65703",
    "birthday": "1996-10-07",
    "body": "175cm, 79kg",
    "handedness": "우투좌타"
  },
  {
    "name": "황영묵",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "95",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54795",
    "birthday": "1999-10-16",
    "body": "177cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김태연",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "25",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66704",
    "birthday": "1997-06-10",
    "body": "178cm, 96kg",
    "handedness": "우투우타"
  },
  {
    "name": "문현빈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "51",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53764",
    "birthday": "2004-04-20",
    "body": "174cm, 82kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이원석",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "37",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68700",
    "birthday": "1999-03-31",
    "body": "177cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "최인호",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "41",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50707",
    "birthday": "2000-01-30",
    "body": "178cm, 82kg",
    "handedness": "우투좌타"
  },
  {
    "name": "페라자",
    "role": "hitter",
    "position": "OF",
    "bats": "S",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "30",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54730",
    "birthday": "1998-11-10",
    "body": "175cm, 88kg",
    "handedness": "우투양타"
  },
  {
    "name": "김관우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "112",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53701",
    "birthday": "2003-09-07",
    "body": "182cm, 97kg",
    "handedness": "우언우타"
  },
  {
    "name": "김서현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "44",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53754",
    "birthday": "2004-05-31",
    "body": "188cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "김승일",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "14",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50711",
    "birthday": "2001-07-07",
    "body": "183cm, 85kg",
    "handedness": "우언우타"
  },
  {
    "name": "김종수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "38",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "63765",
    "birthday": "1994-06-03",
    "body": "180cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "양선률",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "101",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50813",
    "birthday": "1997-04-15",
    "body": "186cm, 91kg",
    "handedness": "우투우타"
  },
  {
    "name": "원종혁",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "48",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54702",
    "birthday": "2005-08-27",
    "body": "184cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "윤산흠",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "49",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69213",
    "birthday": "1999-05-15",
    "body": "178cm, 74kg",
    "handedness": "우투우타"
  },
  {
    "name": "정이황",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "34",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69767",
    "birthday": "2000-03-07",
    "body": "190cm, 89kg",
    "handedness": "우투우타"
  },
  {
    "name": "주현상",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "66",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "65707",
    "birthday": "1992-08-10",
    "body": "177cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "박상언",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "42",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "66707",
    "birthday": "1997-03-03",
    "body": "185cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "장규현",
    "role": "hitter",
    "position": "C",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "32",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51762",
    "birthday": "2002-06-28",
    "body": "183cm, 96kg",
    "handedness": "우투좌타"
  },
  {
    "name": "정우성",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "115",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53008",
    "birthday": "2002-04-11",
    "body": "183cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "김건",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "56",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69702",
    "birthday": "2000-02-23",
    "body": "183cm, 79kg",
    "handedness": "우투우타"
  },
  {
    "name": "이지성",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "4",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55706",
    "birthday": "2005-11-29",
    "body": "180cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "정민규",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "2",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51764",
    "birthday": "2003-01-10",
    "body": "183cm, 101kg",
    "handedness": "우투우타"
  },
  {
    "name": "정은원",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "43",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68743",
    "birthday": "2000-01-17",
    "body": "177cm, 82kg",
    "handedness": "우투좌타"
  },
  {
    "name": "최유빈",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "93",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56793",
    "birthday": "2002-05-27",
    "body": "173cm, 73kg",
    "handedness": "우투좌타"
  },
  {
    "name": "하주석",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "16",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "62700",
    "birthday": "1994-02-25",
    "body": "185cm, 92kg",
    "handedness": "우투좌타"
  },
  {
    "name": "한경빈",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "6",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52710",
    "birthday": "1998-12-11",
    "body": "178cm, 69kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김동휘",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "113",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56713",
    "birthday": "2000-03-30",
    "body": "183cm, 90kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박상목",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "102",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56702",
    "birthday": "2001-03-23",
    "body": "170cm, 73kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "오재원",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "54",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56754",
    "birthday": "2007-01-21",
    "body": "176cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "유로결",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "33",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69766",
    "birthday": "2000-05-30",
    "body": "186cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "이도훈",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "08",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56708",
    "birthday": "2003-08-27",
    "body": "172cm, 74kg",
    "handedness": "우투우타"
  },
  {
    "name": "최윤호",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "114",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56714",
    "birthday": "2000-03-06",
    "body": "175cm, 76kg",
    "handedness": "우투좌타"
  },
  {
    "name": "한지윤",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "36",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55767",
    "birthday": "2006-04-10",
    "body": "188cm, 98kg",
    "handedness": "우투우타"
  }
];
