export default [
  {
    "name": "곽도규",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 22,
    "jerseyNumber": "0",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53609",
    "birthday": "2004-04-12",
    "body": "185cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김범수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 31,
    "jerseyNumber": "49",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65769",
    "birthday": "1995-10-03",
    "body": "181cm, 92kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김태형",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "10",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55610",
    "birthday": "2006-12-15",
    "body": "184cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "네일",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "40",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54640",
    "birthday": "1993-02-08",
    "body": "193cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "성영탁",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "65",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54610",
    "birthday": "2004-07-28",
    "body": "180cm, 89kg",
    "handedness": "우투우타"
  },
  {
    "name": "시라카와",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "63",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54843",
    "birthday": "2001-06-04",
    "body": "180cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "양현종",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 38,
    "jerseyNumber": "54",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "77637",
    "birthday": "1988-03-01",
    "body": "183cm, 91kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "올러",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "33",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55633",
    "birthday": "1994-10-17",
    "body": "193cm, 102kg",
    "handedness": "우투우타"
  },
  {
    "name": "전상현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "51",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66609",
    "birthday": "1996-04-18",
    "body": "180cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "정해영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "62",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50662",
    "birthday": "2001-08-23",
    "body": "189cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "조상우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "11",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63342",
    "birthday": "1994-09-04",
    "body": "186cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "최지민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 23,
    "jerseyNumber": "39",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52639",
    "birthday": "2003-09-10",
    "body": "185cm, 100kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "한재승",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "55",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51994",
    "birthday": "2001-11-21",
    "body": "180cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "황동하",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "41",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52641",
    "birthday": "2002-07-30",
    "body": "183cm, 96kg",
    "handedness": "우투우타"
  },
  {
    "name": "김태군",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "42",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "78122",
    "birthday": "1989-12-30",
    "body": "182cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "한준수",
    "role": "hitter",
    "position": "C",
    "bats": "L",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "25",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68646",
    "birthday": "1999-02-13",
    "body": "184cm, 95kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김규성",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "14",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66614",
    "birthday": "1997-03-08",
    "body": "185cm, 88kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김도영",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "5",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52605",
    "birthday": "2003-10-02",
    "body": "183cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "김선빈",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "3",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "78603",
    "birthday": "1989-12-18",
    "body": "165cm, 77kg",
    "handedness": "우투우타"
  },
  {
    "name": "박민",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "2",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50657",
    "birthday": "2001-06-05",
    "body": "184cm, 84kg",
    "handedness": "우투우타"
  },
  {
    "name": "변우혁",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "29",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69727",
    "birthday": "2000-03-18",
    "body": "185cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "윤도현",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "16",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52667",
    "birthday": "2003-05-07",
    "body": "181cm, 84kg",
    "handedness": "우투우타"
  },
  {
    "name": "정현창",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "12",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55926",
    "birthday": "2006-07-14",
    "body": "177cm, 70kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김민규",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "37",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56637",
    "birthday": "2007-01-26",
    "body": "180cm, 73kg",
    "handedness": "우투우타"
  },
  {
    "name": "김호령",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "27",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65653",
    "birthday": "1992-04-30",
    "body": "178cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "나성범",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 37,
    "jerseyNumber": "47",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62947",
    "birthday": "1989-10-03",
    "body": "183cm, 100kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박재현",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "15",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55636",
    "birthday": "2006-12-08",
    "body": "180cm, 73kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박정우",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 28,
    "jerseyNumber": "1",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67609",
    "birthday": "1998-02-01",
    "body": "175cm, 68kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "카스트로",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "26",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56626",
    "birthday": "1993-11-30",
    "body": "183cm, 88kg",
    "handedness": "우투좌타"
  },
  {
    "name": "강이준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "102",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "67604",
    "birthday": "1998-04-07",
    "body": "190cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "김경묵",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "118",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55618",
    "birthday": "1999-05-07",
    "body": "183cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "김대유",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 35,
    "jerseyNumber": "69",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "60337",
    "birthday": "1991-05-08",
    "body": "187cm, 92kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김상범",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "121",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56621",
    "birthday": "2002-10-28",
    "body": "190cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "김현수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "17",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69516",
    "birthday": "2000-07-10",
    "body": "185cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "유지성",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "4",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50604",
    "birthday": "2000-11-15",
    "body": "189cm, 94kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "윤중현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "19",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68619",
    "birthday": "1995-04-25",
    "body": "180cm, 84kg",
    "handedness": "우언우타"
  },
  {
    "name": "이호진",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 23,
    "jerseyNumber": "124",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56624",
    "birthday": "2003-10-22",
    "body": "187cm, 94kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "장재혁",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "38",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50641",
    "birthday": "2001-08-02",
    "body": "180cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "조건호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "112",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56612",
    "birthday": "2002-05-09",
    "body": "182cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "신명승",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "142",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52642",
    "birthday": "2002-11-02",
    "body": "183cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "주효상",
    "role": "hitter",
    "position": "C",
    "bats": "L",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "22",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "66354",
    "birthday": "1997-11-11",
    "body": "183cm, 95kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박상준",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "50",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52634",
    "birthday": "2001-08-21",
    "body": "178cm, 104kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박종혁",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "133",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56634",
    "birthday": "2007-10-05",
    "body": "190cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "엄준현",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "131",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55631",
    "birthday": "2006-04-20",
    "body": "174cm, 75kg",
    "handedness": "우투우타"
  },
  {
    "name": "이호연",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "36",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68504",
    "birthday": "1995-06-03",
    "body": "177cm, 87kg",
    "handedness": "우투좌타"
  },
  {
    "name": "차상현",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "134",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56636",
    "birthday": "2003-01-26",
    "body": "175cm, 77kg",
    "handedness": "우투우타"
  },
  {
    "name": "최정용",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "23",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "65464",
    "birthday": "1996-10-24",
    "body": "179cm, 84kg",
    "handedness": "우투좌타"
  },
  {
    "name": "한준희",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "119",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56619",
    "birthday": "2007-07-01",
    "body": "183cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "황대인",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "34",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "65610",
    "birthday": "1996-02-10",
    "body": "178cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "고종욱",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "57",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "61353",
    "birthday": "1989-01-11",
    "body": "184cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "곽동효",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "138",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56638",
    "birthday": "2002-12-22",
    "body": "180cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "박헌",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "113",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55637",
    "birthday": "2006-01-05",
    "body": "185cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이창진",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 35,
    "jerseyNumber": "8",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64560",
    "birthday": "1991-03-04",
    "body": "173cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "정해원",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "9",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53659",
    "birthday": "2004-05-21",
    "body": "185cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "한승연",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "31",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52628",
    "birthday": "2003-06-09",
    "body": "183cm, 92kg",
    "handedness": "우투우타"
  }
];
