export default [
  {
    "name": "김동규",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "99",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53164",
    "birthday": "2004-07-09",
    "body": "194cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "김윤하",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "19",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54319",
    "birthday": "2005-03-07",
    "body": "185cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "박정훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "94",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55394",
    "birthday": "2006-03-23",
    "body": "192cm, 103kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박지성",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "37",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56337",
    "birthday": "2007-03-16",
    "body": "190cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "배동현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "61",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51761",
    "birthday": "1998-03-16",
    "body": "183cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "안우진",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "41",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68341",
    "birthday": "1999-08-30",
    "body": "192cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "알칸타라",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "54",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69045",
    "birthday": "1992-12-04",
    "body": "193cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "원종현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 39,
    "jerseyNumber": "46",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "76118",
    "birthday": "1987-07-31",
    "body": "182cm, 88kg",
    "handedness": "우언우타"
  },
  {
    "name": "유토",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "48",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56348",
    "birthday": "1999-11-04",
    "body": "185cm, 87kg",
    "handedness": "우투좌타"
  },
  {
    "name": "전준표",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "62",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54362",
    "birthday": "2005-05-07",
    "body": "186cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "정다훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "45",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56345",
    "birthday": "2006-07-06",
    "body": "183cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "조영건",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "20",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69360",
    "birthday": "1999-02-04",
    "body": "180cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "하영민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "50",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64350",
    "birthday": "1995-05-07",
    "body": "183cm, 74kg",
    "handedness": "우투우타"
  },
  {
    "name": "김건희",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "12",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53312",
    "birthday": "2004-11-07",
    "body": "186cm, 96kg",
    "handedness": "우투우타"
  },
  {
    "name": "김동헌",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "44",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53344",
    "birthday": "2004-07-15",
    "body": "182cm, 91kg",
    "handedness": "우투우타"
  },
  {
    "name": "권혁빈",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "00",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55371",
    "birthday": "2005-11-04",
    "body": "185cm, 75kg",
    "handedness": "우투우타"
  },
  {
    "name": "김웅빈",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "10",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65898",
    "birthday": "1996-02-09",
    "body": "182cm, 97kg",
    "handedness": "우투좌타"
  },
  {
    "name": "서건창",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "14",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "78168",
    "birthday": "1989-08-22",
    "body": "176cm, 84kg",
    "handedness": "우투좌타"
  },
  {
    "name": "안치홍",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "9",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "79608",
    "birthday": "1990-07-02",
    "body": "178cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "어준서",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "92",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55392",
    "birthday": "2006-11-27",
    "body": "183cm, 87kg",
    "handedness": "우투좌타"
  },
  {
    "name": "여동욱",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "93",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55393",
    "birthday": "2005-11-10",
    "body": "180cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "최재영",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "38",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56338",
    "birthday": "2007-01-08",
    "body": "183cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "최주환",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 38,
    "jerseyNumber": "53",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "76267",
    "birthday": "1988-02-28",
    "body": "177cm, 73kg",
    "handedness": "우투좌타"
  },
  {
    "name": "히우라",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "22",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56305",
    "birthday": "1996-08-02",
    "body": "178cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "박찬혁",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "43",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52348",
    "birthday": "2003-04-25",
    "body": "181cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "임병욱",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "17",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64346",
    "birthday": "1995-09-30",
    "body": "187cm, 94kg",
    "handedness": "우투좌타"
  },
  {
    "name": "추재현",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 27,
    "jerseyNumber": "27",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68362",
    "birthday": "1999-02-22",
    "body": "178cm, 85kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김선기",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 35,
    "jerseyNumber": "49",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "66018",
    "birthday": "1991-09-01",
    "body": "187cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "김성민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 32,
    "jerseyNumber": "8",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "67828",
    "birthday": "1994-04-26",
    "body": "181cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박진형",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "40",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "63512",
    "birthday": "1994-06-10",
    "body": "181cm, 77kg",
    "handedness": "우투우타"
  },
  {
    "name": "오석주",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "31",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "67116",
    "birthday": "1998-04-14",
    "body": "180cm, 74kg",
    "handedness": "우투우타"
  },
  {
    "name": "이승재",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "118",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56308",
    "birthday": "2005-04-07",
    "body": "183cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "이준우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "42",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55301",
    "birthday": "2001-03-02",
    "body": "183cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "이태준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "109",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54301",
    "birthday": "2005-11-27",
    "body": "183cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "임진묵",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "69",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55382",
    "birthday": "2006-04-23",
    "body": "181cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "정세영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "64",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55377",
    "birthday": "2006-09-23",
    "body": "177cm, 82kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "한민우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 27,
    "jerseyNumber": "110",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53096",
    "birthday": "1999-04-27",
    "body": "178cm, 82kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김시앙",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "121",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51303",
    "birthday": "2001-10-31",
    "body": "177cm, 84kg",
    "handedness": "우투우타"
  },
  {
    "name": "김재현",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "32",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "62332",
    "birthday": "1993-03-18",
    "body": "178cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김지성",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "105",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54397",
    "birthday": "2004-05-27",
    "body": "174cm, 91kg",
    "handedness": "우투우타"
  },
  {
    "name": "박성빈",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "56",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53305",
    "birthday": "2004-04-21",
    "body": "177cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "김지석",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "26",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56326",
    "birthday": "2007-02-19",
    "body": "185cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김태진",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "1",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64984",
    "birthday": "1995-10-07",
    "body": "169cm, 73kg",
    "handedness": "우투좌타"
  },
  {
    "name": "서유신",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "104",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53309",
    "birthday": "2000-08-17",
    "body": "176cm, 76kg",
    "handedness": "우투우타"
  },
  {
    "name": "오선진",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "6",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "78756",
    "birthday": "1989-07-07",
    "body": "178cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "유정택",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "115",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56315",
    "birthday": "2003-11-20",
    "body": "170cm, 70kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이재상",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "5",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54305",
    "birthday": "2005-04-17",
    "body": "183cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "이주형",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "58",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51302",
    "birthday": "2002-07-05",
    "body": "183cm, 105kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박채울",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "72",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54303",
    "birthday": "2004-11-20",
    "body": "185cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "심휘윤",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "111",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54306",
    "birthday": "2005-05-28",
    "body": "183cm, 84kg",
    "handedness": "우투우타"
  },
  {
    "name": "원성준",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "33",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54307",
    "birthday": "2000-03-31",
    "body": "181cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "임지열",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "29",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64340",
    "birthday": "1995-08-22",
    "body": "180cm, 94kg",
    "handedness": "우투우타"
  }
];
