export default [
  {
    "name": "고영표",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 35,
    "jerseyNumber": "1",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64001",
    "birthday": "1991-09-16",
    "body": "187cm, 88kg",
    "handedness": "우언우타"
  },
  {
    "name": "김민수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "26",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65048",
    "birthday": "1992-07-24",
    "body": "188cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "로건",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 29,
    "jerseyNumber": "43",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55912",
    "birthday": "1997-05-23",
    "body": "186cm, 105kg",
    "handedness": "좌투우타"
  },
  {
    "name": "박영현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "60",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52060",
    "birthday": "2003-10-11",
    "body": "183cm, 91kg",
    "handedness": "우투우타"
  },
  {
    "name": "사우어",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "32",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56032",
    "birthday": "1999-01-21",
    "body": "193cm, 104kg",
    "handedness": "우투우타"
  },
  {
    "name": "소형준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "30",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50030",
    "birthday": "2001-09-16",
    "body": "189cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "손동현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "41",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69041",
    "birthday": "2001-01-23",
    "body": "183cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "스기모토",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "11",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56011",
    "birthday": "2000-05-19",
    "body": "182cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "오원석",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "47",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50859",
    "birthday": "2001-04-23",
    "body": "182cm, 80kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "우규민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 41,
    "jerseyNumber": "12",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "73117",
    "birthday": "1985-01-21",
    "body": "184cm, 75kg",
    "handedness": "우언우타"
  },
  {
    "name": "이상동",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "37",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69054",
    "birthday": "1995-11-24",
    "body": "181cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "주권",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "38",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65060",
    "birthday": "1995-05-31",
    "body": "181cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "한차현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "2",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51058",
    "birthday": "1998-11-30",
    "body": "180cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "조대현",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "42",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68089",
    "birthday": "1999-08-06",
    "body": "183cm, 81kg",
    "handedness": "우투우타"
  },
  {
    "name": "한승택",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "45",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63722",
    "birthday": "1994-06-21",
    "body": "174cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "권동진",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "52",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51003",
    "birthday": "1998-09-12",
    "body": "178cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김상수",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "7",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "79402",
    "birthday": "1990-03-23",
    "body": "175cm, 68kg",
    "handedness": "우투우타"
  },
  {
    "name": "류현인",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "9",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53036",
    "birthday": "2000-11-08",
    "body": "174cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "오윤석",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "4",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64504",
    "birthday": "1992-02-24",
    "body": "180cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "장준원",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "56",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64115",
    "birthday": "1995-11-21",
    "body": "183cm, 77kg",
    "handedness": "우투우타"
  },
  {
    "name": "허경민",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "13",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "79240",
    "birthday": "1990-08-26",
    "body": "176cm, 69kg",
    "handedness": "우투우타"
  },
  {
    "name": "힐리어드",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "L",
    "age": 32,
    "jerseyNumber": "34",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56034",
    "birthday": "1994-02-21",
    "body": "196cm, 107kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김민혁",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "53",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64004",
    "birthday": "1995-11-21",
    "body": "181cm, 71kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김현수",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 38,
    "jerseyNumber": "10",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "76290",
    "birthday": "1988-01-12",
    "body": "188cm, 105kg",
    "handedness": "우투좌타"
  },
  {
    "name": "안현민",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "23",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52001",
    "birthday": "2003-08-22",
    "body": "183cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "이정훈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "33",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67644",
    "birthday": "1994-12-07",
    "body": "185cm, 90kg",
    "handedness": "우투좌타"
  },
  {
    "name": "장진혁",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "51",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66706",
    "birthday": "1993-09-30",
    "body": "184cm, 90kg",
    "handedness": "우투좌타"
  },
  {
    "name": "최원준",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "3",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66606",
    "birthday": "1997-03-23",
    "body": "178cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "고준혁",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 21,
    "jerseyNumber": "68",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56068",
    "birthday": "2005-05-29",
    "body": "186cm, 81kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김규한",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "116",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56016",
    "birthday": "2001-03-17",
    "body": "182cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "문용익",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "18",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "67419",
    "birthday": "1995-02-04",
    "body": "178cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "박건우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "46",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55046",
    "birthday": "2006-11-28",
    "body": "182cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "박지훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "66",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56066",
    "birthday": "2007-01-19",
    "body": "188cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "이채호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "17",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68896",
    "birthday": "1998-11-23",
    "body": "185cm, 85kg",
    "handedness": "우언우타"
  },
  {
    "name": "장민호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "100",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55010",
    "birthday": "2002-07-05",
    "body": "180cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "전용주",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "29",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69047",
    "birthday": "2000-02-12",
    "body": "188cm, 87kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "지명성",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "39",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51060",
    "birthday": "2002-02-15",
    "body": "173cm, 65kg",
    "handedness": "우투우타"
  },
  {
    "name": "최동환",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "16",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "79140",
    "birthday": "1989-09-19",
    "body": "184cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "강현우",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "55",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50066",
    "birthday": "2001-04-13",
    "body": "180cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김민석",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "44",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54097",
    "birthday": "2005-07-22",
    "body": "181cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "문상철",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 35,
    "jerseyNumber": "24",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64007",
    "birthday": "1991-04-06",
    "body": "184cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "박성준",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "120",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56020",
    "birthday": "2003-07-28",
    "body": "168cm, 71kg",
    "handedness": "우투좌타"
  },
  {
    "name": "손민석",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "57",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53057",
    "birthday": "2004-06-21",
    "body": "177cm, 70kg",
    "handedness": "우투좌타"
  },
  {
    "name": "안인산",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "50",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50901",
    "birthday": "2001-02-27",
    "body": "181cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "오서진",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "25",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55005",
    "birthday": "2006-02-22",
    "body": "188cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "이강민",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "6",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56006",
    "birthday": "2007-01-27",
    "body": "181cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "이용현",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "106",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55006",
    "birthday": "2006-01-06",
    "body": "188cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "임상우",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "94",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56001",
    "birthday": "2003-01-03",
    "body": "180cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김경환",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "109",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56009",
    "birthday": "2007-01-04",
    "body": "181cm, 78kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박민석",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "104",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55004",
    "birthday": "2006-07-27",
    "body": "178cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "배정대",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "27",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64166",
    "birthday": "1995-06-12",
    "body": "185cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "안치영",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "8",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "67006",
    "birthday": "1998-05-29",
    "body": "176cm, 72kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이재원",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "65",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56005",
    "birthday": "2007-04-27",
    "body": "180cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "정영웅",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 27,
    "jerseyNumber": "108",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55008",
    "birthday": "1999-12-25",
    "body": "171cm, 75kg",
    "handedness": "좌투좌타"
  }
];
