export default [
  {
    "name": "김영우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "67",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55167",
    "birthday": "2005-01-14",
    "body": "185cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김윤식",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "47",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50157",
    "birthday": "2000-04-03",
    "body": "181cm, 83kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김진성",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 41,
    "jerseyNumber": "42",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "75867",
    "birthday": "1985-03-07",
    "body": "186cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김진수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "45",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51154",
    "birthday": "1998-08-31",
    "body": "179cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "리오스",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "46",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56146",
    "birthday": "1993-06-27",
    "body": "190cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "박시원",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "58",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55121",
    "birthday": "2006-04-12",
    "body": "193cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "손주영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 28,
    "jerseyNumber": "29",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67143",
    "birthday": "1998-12-02",
    "body": "191cm, 95kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "우강훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "20",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51526",
    "birthday": "2002-10-03",
    "body": "183cm, 88kg",
    "handedness": "우언우타"
  },
  {
    "name": "웰스",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 29,
    "jerseyNumber": "68",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55348",
    "birthday": "1997-02-27",
    "body": "185cm, 83kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이우찬",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 34,
    "jerseyNumber": "21",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "61145",
    "birthday": "1992-08-04",
    "body": "185cm, 97kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "임찬규",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "1",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "61101",
    "birthday": "1992-11-20",
    "body": "185cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "장현식",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "50",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63950",
    "birthday": "1995-02-24",
    "body": "181cm, 91kg",
    "handedness": "우투우타"
  },
  {
    "name": "조원태",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 23,
    "jerseyNumber": "38",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52149",
    "birthday": "2003-05-10",
    "body": "186cm, 92kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "톨허스트",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "30",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55130",
    "birthday": "1999-09-13",
    "body": "193cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "함덕주",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 31,
    "jerseyNumber": "11",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63248",
    "birthday": "1995-01-13",
    "body": "181cm, 78kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박동원",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "27",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "79365",
    "birthday": "1990-04-07",
    "body": "178cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "이주헌",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "63",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52154",
    "birthday": "2003-03-04",
    "body": "185cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "구본혁",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "6",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69100",
    "birthday": "1997-01-11",
    "body": "177cm, 75kg",
    "handedness": "우투우타"
  },
  {
    "name": "문보경",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "2",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69102",
    "birthday": "2000-07-19",
    "body": "182cm, 88kg",
    "handedness": "우투좌타"
  },
  {
    "name": "문정빈",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "56",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52121",
    "birthday": "2003-08-15",
    "body": "186cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "신민재",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "4",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65207",
    "birthday": "1996-01-21",
    "body": "171cm, 67kg",
    "handedness": "우투좌타"
  },
  {
    "name": "오스틴",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "23",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53123",
    "birthday": "1993-10-14",
    "body": "183cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "오지환",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "10",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "79109",
    "birthday": "1990-03-12",
    "body": "185cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이영빈",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "7",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51100",
    "birthday": "2002-06-17",
    "body": "182cm, 82kg",
    "handedness": "우투좌타"
  },
  {
    "name": "천성호",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "53",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50054",
    "birthday": "1997-10-30",
    "body": "183cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "문성주",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 29,
    "jerseyNumber": "8",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68119",
    "birthday": "1997-02-20",
    "body": "175cm, 78kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박해민",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "17",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62415",
    "birthday": "1990-02-24",
    "body": "180cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "송찬의",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "55",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68110",
    "birthday": "1999-02-20",
    "body": "182cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "홍창기",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "51",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66108",
    "birthday": "1993-11-21",
    "body": "189cm, 94kg",
    "handedness": "우투좌타"
  },
  {
    "name": "권우준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "49",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56149",
    "birthday": "2007-01-08",
    "body": "187cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "김동현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "43",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56143",
    "birthday": "2005-03-03",
    "body": "190cm, 96kg",
    "handedness": "우투우타"
  },
  {
    "name": "김유영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 32,
    "jerseyNumber": "0",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64596",
    "birthday": "1994-05-02",
    "body": "180cm, 83kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "양우진",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "65",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56165",
    "birthday": "2007-06-05",
    "body": "190cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "오승윤",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "123",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54105",
    "birthday": "2001-06-25",
    "body": "178cm, 84kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이상영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "39",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69168",
    "birthday": "2000-12-03",
    "body": "193cm, 95kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "정우영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "18",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69159",
    "birthday": "1999-08-19",
    "body": "193cm, 99kg",
    "handedness": "우언우타"
  },
  {
    "name": "조건희",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "48",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51163",
    "birthday": "2002-03-26",
    "body": "184cm, 84kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "진우영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "101",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54148",
    "birthday": "2001-02-05",
    "body": "188cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "허준혁",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "129",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52119",
    "birthday": "1999-07-02",
    "body": "180cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "강민기",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "102",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56102",
    "birthday": "2007-09-14",
    "body": "184cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "김준태",
    "role": "hitter",
    "position": "C",
    "bats": "L",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "44",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "62558",
    "birthday": "1994-07-31",
    "body": "175cm, 91kg",
    "handedness": "우투좌타"
  },
  {
    "name": "전경원",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "128",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68869",
    "birthday": "1999-03-18",
    "body": "184cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "강민균",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "00",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53103",
    "birthday": "2000-07-17",
    "body": "178cm, 81kg",
    "handedness": "우투우타"
  },
  {
    "name": "곽민호",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "124",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53104",
    "birthday": "2004-12-23",
    "body": "184cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김성진",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "36",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69105",
    "birthday": "2000-03-17",
    "body": "183cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "김정율",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "14",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "67504",
    "birthday": "1998-03-18",
    "body": "184cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "손용준",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "15",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54156",
    "birthday": "2000-02-15",
    "body": "178cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "추세현",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "35",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55163",
    "birthday": "2006-04-19",
    "body": "187cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김주성",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "5",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "66162",
    "birthday": "1998-01-30",
    "body": "180cm, 81kg",
    "handedness": "우투우타"
  },
  {
    "name": "김현종",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "66",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54166",
    "birthday": "2004-08-04",
    "body": "186cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "박현우",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "108",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56108",
    "birthday": "2005-02-20",
    "body": "183cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "서영준",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "60",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55160",
    "birthday": "2006-03-18",
    "body": "186cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "엄태경",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "104",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52124",
    "birthday": "2003-05-03",
    "body": "184cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이재원",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "52",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68106",
    "birthday": "1999-07-17",
    "body": "192cm, 105kg",
    "handedness": "우투우타"
  },
  {
    "name": "함창건",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "24",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50108",
    "birthday": "2001-08-18",
    "body": "176cm, 83kg",
    "handedness": "좌투좌타"
  }
];
