export default [
  {
    "name": "김강현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "19",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65522",
    "birthday": "1995-02-27",
    "body": "177cm, 84kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김기준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "47",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53540",
    "birthday": "2004-04-16",
    "body": "188cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김원중",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "34",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62528",
    "birthday": "1993-06-14",
    "body": "192cm, 96kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김진욱",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "15",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51516",
    "birthday": "2002-07-05",
    "body": "185cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "나균안",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "43",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67539",
    "birthday": "1998-03-16",
    "body": "186cm, 109kg",
    "handedness": "우투우타"
  },
  {
    "name": "로드리게스",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "31",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56531",
    "birthday": "1998-03-31",
    "body": "193cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "박세웅",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "21",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64021",
    "birthday": "1995-11-30",
    "body": "182cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "비슬리",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "23",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56523",
    "birthday": "1995-11-20",
    "body": "188cm, 106kg",
    "handedness": "우투우타"
  },
  {
    "name": "이이무라",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "39",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56503",
    "birthday": "1998-04-28",
    "body": "183cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "이진하",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "45",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53562",
    "birthday": "2004-06-02",
    "body": "191cm, 96kg",
    "handedness": "우투우타"
  },
  {
    "name": "최준용",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "56",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50556",
    "birthday": "2001-10-10",
    "body": "185cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "현도훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "17",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68260",
    "birthday": "1993-01-13",
    "body": "188cm, 95kg",
    "handedness": "우투좌타"
  },
  {
    "name": "홍민기",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "38",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50596",
    "birthday": "2001-07-20",
    "body": "185cm, 85kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박건우",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "69",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55509",
    "birthday": "2003-02-01",
    "body": "183cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "손성빈",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "28",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51528",
    "birthday": "2002-01-14",
    "body": "186cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "고승민",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "2",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69517",
    "birthday": "2000-08-11",
    "body": "189cm, 92kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김세민",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "5",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52514",
    "birthday": "2003-06-14",
    "body": "183cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "나승엽",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "51",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51551",
    "birthday": "2002-02-15",
    "body": "190cm, 82kg",
    "handedness": "우투좌타"
  },
  {
    "name": "노진혁",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "52",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62931",
    "birthday": "1989-07-15",
    "body": "184cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박승욱",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "53",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62802",
    "birthday": "1992-12-04",
    "body": "184cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박찬형",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "60",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55530",
    "birthday": "2002-10-17",
    "body": "175cm, 78kg",
    "handedness": "우투좌타"
  },
  {
    "name": "전민재",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "13",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68205",
    "birthday": "1999-06-30",
    "body": "181cm, 73kg",
    "handedness": "우투우타"
  },
  {
    "name": "한동희",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "25",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68525",
    "birthday": "1999-06-01",
    "body": "182cm, 108kg",
    "handedness": "우투우타"
  },
  {
    "name": "김동혁",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "50",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52504",
    "birthday": "2000-09-15",
    "body": "177cm, 77kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "레이예스",
    "role": "hitter",
    "position": "OF",
    "bats": "S",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "29",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54529",
    "birthday": "1994-10-05",
    "body": "196cm, 87kg",
    "handedness": "우투양타"
  },
  {
    "name": "손호영",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "33",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50150",
    "birthday": "1994-08-23",
    "body": "182cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "윤동희",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "91",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52591",
    "birthday": "2003-09-18",
    "body": "187cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "황성빈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "0",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50500",
    "birthday": "1997-12-19",
    "body": "172cm, 76kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김창훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "66",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51586",
    "birthday": "2001-11-09",
    "body": "185cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "박정민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "36",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56536",
    "birthday": "2003-09-26",
    "body": "188cm, 95kg",
    "handedness": "우투좌타"
  },
  {
    "name": "석상호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "133",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53560",
    "birthday": "2000-04-14",
    "body": "182cm, 102kg",
    "handedness": "우투우타"
  },
  {
    "name": "손준이",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "143",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56544",
    "birthday": "2004-01-07",
    "body": "185cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "송재영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "59",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51594",
    "birthday": "2002-06-20",
    "body": "181cm, 84kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이영재",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "40",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55503",
    "birthday": "2006-10-20",
    "body": "180cm, 71kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "장세진",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 22,
    "jerseyNumber": "131",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53596",
    "birthday": "2004-12-30",
    "body": "179cm, 80kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "정성종",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "18",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68556",
    "birthday": "1995-11-16",
    "body": "181cm, 93kg",
    "handedness": "우투좌타"
  },
  {
    "name": "정현수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "57",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54537",
    "birthday": "2001-05-10",
    "body": "180cm, 84kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "하혜성",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "118",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52560",
    "birthday": "2003-06-09",
    "body": "191cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "김현도",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "109",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56509",
    "birthday": "2002-04-26",
    "body": "173cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "정문혁",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "32",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56543",
    "birthday": "2007-02-24",
    "body": "185cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "정보근",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "42",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68518",
    "birthday": "1999-08-31",
    "body": "175cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "김민성",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 38,
    "jerseyNumber": "16",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "77564",
    "birthday": "1988-12-17",
    "body": "181cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "김호범",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "112",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56512",
    "birthday": "2003-08-16",
    "body": "186cm, 88kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이서준",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "63",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56563",
    "birthday": "2007-10-10",
    "body": "183cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "이지훈",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "114",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56514",
    "birthday": "2003-01-13",
    "body": "171cm, 66kg",
    "handedness": "우투우타"
  },
  {
    "name": "정대선",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "4",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53568",
    "birthday": "2004-11-16",
    "body": "185cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "홍서연",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "119",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56519",
    "birthday": "2003-10-12",
    "body": "184cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "김동현",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "64",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55502",
    "birthday": "2004-12-30",
    "body": "185cm, 100kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김한홀",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "95",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56595",
    "birthday": "2006-12-12",
    "body": "189cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "신윤후",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "3",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69508",
    "birthday": "1996-01-05",
    "body": "177cm, 77kg",
    "handedness": "우투우타"
  },
  {
    "name": "유제모",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "142",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54513",
    "birthday": "2003-02-26",
    "body": "178cm, 78kg",
    "handedness": "우투좌타"
  },
  {
    "name": "전준우",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 40,
    "jerseyNumber": "8",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "78513",
    "birthday": "1986-02-25",
    "body": "184cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "조민영",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "134",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55534",
    "birthday": "2005-03-24",
    "body": "186cm, 92kg",
    "handedness": "우투우타"
  }
];
