export default [
  {
    "name": "구창모",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 29,
    "jerseyNumber": "59",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65933",
    "birthday": "1997-02-17",
    "body": "183cm, 85kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김진호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "54",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67954",
    "birthday": "1998-06-07",
    "body": "183cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "김태경",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "60",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50992",
    "birthday": "2001-04-07",
    "body": "188cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "김태훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "69",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55995",
    "birthday": "2006-10-26",
    "body": "188cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "라일리",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "3",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55903",
    "birthday": "1996-07-09",
    "body": "190cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "손주환",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "46",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54904",
    "birthday": "2002-01-05",
    "body": "177cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "송명기",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "45",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69962",
    "birthday": "2000-08-09",
    "body": "191cm, 102kg",
    "handedness": "우투좌타"
  },
  {
    "name": "신영우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "43",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53919",
    "birthday": "2004-04-21",
    "body": "182cm, 84kg",
    "handedness": "우투우타"
  },
  {
    "name": "임지민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "19",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52902",
    "birthday": "2003-10-11",
    "body": "185cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "전사민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "57",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69969",
    "birthday": "1999-07-06",
    "body": "194cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "최우석",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "64",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54903",
    "birthday": "2005-03-31",
    "body": "190cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "테일러",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "66",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56966",
    "birthday": "1995-07-25",
    "body": "198cm, 106kg",
    "handedness": "우투우타"
  },
  {
    "name": "토다",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "11",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56911",
    "birthday": "2000-07-22",
    "body": "170cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "하준영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 27,
    "jerseyNumber": "29",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68639",
    "birthday": "1999-09-06",
    "body": "182cm, 79kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김형준",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "25",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68912",
    "birthday": "1999-11-02",
    "body": "187cm, 98kg",
    "handedness": "우투우타"
  },
  {
    "name": "안중열",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "22",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64022",
    "birthday": "1995-09-01",
    "body": "176cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "김주원",
    "role": "hitter",
    "position": "IF",
    "bats": "S",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "7",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51907",
    "birthday": "2002-07-30",
    "body": "185cm, 83kg",
    "handedness": "우투양타"
  },
  {
    "name": "김한별",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "13",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50902",
    "birthday": "2001-01-18",
    "body": "177cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "김휘집",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "44",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51344",
    "birthday": "2002-01-01",
    "body": "180cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "도태훈",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "16",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66965",
    "birthday": "1993-03-18",
    "body": "184cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박민우",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "2",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62907",
    "birthday": "1993-02-06",
    "body": "185cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "신재인",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "9",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56909",
    "birthday": "2007-06-28",
    "body": "185cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "최정원",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "14",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69992",
    "birthday": "2000-06-24",
    "body": "176cm, 70kg",
    "handedness": "우투좌타"
  },
  {
    "name": "권희동",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "36",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63963",
    "birthday": "1990-12-30",
    "body": "177cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "박건우",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "37",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "79215",
    "birthday": "1990-09-08",
    "body": "184cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "오장한",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "65",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51991",
    "birthday": "2002-05-20",
    "body": "185cm, 90kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이우성",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "55",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63260",
    "birthday": "1994-07-17",
    "body": "182cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "천재환",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "23",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67905",
    "birthday": "1994-04-01",
    "body": "181cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "한석현",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 32,
    "jerseyNumber": "33",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64101",
    "birthday": "1994-05-17",
    "body": "181cm, 73kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김재열",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "21",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "64580",
    "birthday": "1996-01-02",
    "body": "183cm, 97kg",
    "handedness": "우투우타"
  },
  {
    "name": "노재원",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "110",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53914",
    "birthday": "2001-07-26",
    "body": "179cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "박동수",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "111",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52994",
    "birthday": "1999-05-24",
    "body": "177cm, 85kg",
    "handedness": "우투양타"
  },
  {
    "name": "박지한",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "56",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69994",
    "birthday": "2000-10-21",
    "body": "185cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "원종해",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 21,
    "jerseyNumber": "63",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54906",
    "birthday": "2005-04-09",
    "body": "183cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "조민석",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "47",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52903",
    "birthday": "1998-12-21",
    "body": "180cm, 81kg",
    "handedness": "우투좌타"
  },
  {
    "name": "최성영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 29,
    "jerseyNumber": "26",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "66920",
    "birthday": "1997-04-28",
    "body": "180cm, 85kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "최요한",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 19,
    "jerseyNumber": "67",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56967",
    "birthday": "2007-10-16",
    "body": "180cm, 80kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김정호",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "42",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51903",
    "birthday": "1998-07-13",
    "body": "172cm, 84kg",
    "handedness": "우투우타"
  },
  {
    "name": "박성재",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "102",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52980",
    "birthday": "2003-03-21",
    "body": "179cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "이희성",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "32",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56932",
    "birthday": "2007-04-01",
    "body": "185cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "김건",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "52",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56952",
    "birthday": "2007-05-23",
    "body": "180cm, 81kg",
    "handedness": "우투좌타"
  },
  {
    "name": "서호철",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "5",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69995",
    "birthday": "1996-10-16",
    "body": "179cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "오태양",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "6",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51996",
    "birthday": "2002-04-25",
    "body": "180cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "윤준혁",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "31",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50092",
    "birthday": "2001-07-26",
    "body": "186cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "이한",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "122",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52907",
    "birthday": "2003-08-25",
    "body": "181cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "한재환",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "35",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50903",
    "birthday": "2001-10-19",
    "body": "177cm, 89kg",
    "handedness": "우투우타"
  },
  {
    "name": "홍종표",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "10",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50600",
    "birthday": "2000-05-02",
    "body": "178cm, 72kg",
    "handedness": "우투좌타"
  },
  {
    "name": "고준휘",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 19,
    "jerseyNumber": "49",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56949",
    "birthday": "2007-08-12",
    "body": "181cm, 85kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김범준",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "115",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69980",
    "birthday": "2000-04-20",
    "body": "183cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "박시원",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "53",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50996",
    "birthday": "2001-05-30",
    "body": "185cm, 85kg",
    "handedness": "우투좌타"
  },
  {
    "name": "박영빈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "119",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50906",
    "birthday": "1997-07-16",
    "body": "182cm, 88kg",
    "handedness": "우투좌타"
  },
  {
    "name": "장창훈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "123",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55993",
    "birthday": "2000-05-22",
    "body": "176cm, 70kg",
    "handedness": "우투좌타"
  }
];
