export default [
  {
    "name": "김재윤",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 36,
    "jerseyNumber": "62",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65062",
    "birthday": "1990-09-16",
    "body": "185cm, 91kg",
    "handedness": "우투우타"
  },
  {
    "name": "김태훈",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "27",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62360",
    "birthday": "1992-03-02",
    "body": "187cm, 101kg",
    "handedness": "우투우타"
  },
  {
    "name": "백정현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 39,
    "jerseyNumber": "29",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "77446",
    "birthday": "1987-07-13",
    "body": "184cm, 80kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "양창섭",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "42",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68415",
    "birthday": "1999-09-22",
    "body": "182cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "오러클린",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "64",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56464",
    "birthday": "2000-03-14",
    "body": "196cm, 101kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "원태인",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "18",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69446",
    "birthday": "2000-04-06",
    "body": "183cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "이승민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 26,
    "jerseyNumber": "28",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50464",
    "birthday": "2000-08-26",
    "body": "174cm, 79kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이승현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 35,
    "jerseyNumber": "26",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "60146",
    "birthday": "1991-11-20",
    "body": "181cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "이재익",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 32,
    "jerseyNumber": "45",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63492",
    "birthday": "1994-03-18",
    "body": "180cm, 76kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "임기영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "38",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62754",
    "birthday": "1993-04-16",
    "body": "184cm, 86kg",
    "handedness": "우언우타"
  },
  {
    "name": "장찬희",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "60",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56460",
    "birthday": "2007-10-05",
    "body": "186cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "최지광",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "11",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67421",
    "birthday": "1998-03-13",
    "body": "173cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "후라도",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "75",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53375",
    "birthday": "1996-01-30",
    "body": "188cm, 109kg",
    "handedness": "우투우타"
  },
  {
    "name": "강민호",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 41,
    "jerseyNumber": "47",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "74540",
    "birthday": "1985-08-18",
    "body": "185cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "김도환",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "24",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69442",
    "birthday": "2000-04-14",
    "body": "178cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "장승현",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "46",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "63202",
    "birthday": "1994-03-07",
    "body": "184cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "김상준",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "56",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55425",
    "birthday": "2002-12-30",
    "body": "176cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "디아즈",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "L",
    "age": 30,
    "jerseyNumber": "0",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54400",
    "birthday": "1996-11-19",
    "body": "188cm, 105kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "류지혁",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "16",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62234",
    "birthday": "1994-01-13",
    "body": "181cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "심재훈",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "6",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55438",
    "birthday": "2006-03-03",
    "body": "180cm, 80kg",
    "handedness": "우투우타"
  },
  {
    "name": "양우현",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "53",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69403",
    "birthday": "2000-04-13",
    "body": "175cm, 82kg",
    "handedness": "우투좌타"
  },
  {
    "name": "전병우",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "61",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "65586",
    "birthday": "1992-10-24",
    "body": "182cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "구자욱",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "5",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62404",
    "birthday": "1993-02-12",
    "body": "189cm, 75kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김성윤",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 27,
    "jerseyNumber": "39",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67449",
    "birthday": "1999-02-02",
    "body": "163cm, 62kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김지찬",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "58",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50458",
    "birthday": "2001-03-08",
    "body": "163cm, 64kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김헌곤",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 38,
    "jerseyNumber": "32",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "61404",
    "birthday": "1988-11-09",
    "body": "174cm, 81kg",
    "handedness": "우투우타"
  },
  {
    "name": "김현준",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "44",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51417",
    "birthday": "2002-10-11",
    "body": "178cm, 78kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "박승규",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "66",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "69418",
    "birthday": "2000-09-02",
    "body": "178cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "최형우",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 43,
    "jerseyNumber": "34",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "72443",
    "birthday": "1983-12-16",
    "body": "180cm, 106kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김동현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "123",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54402",
    "birthday": "2001-05-25",
    "body": "186cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "김백산",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "113",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55420",
    "birthday": "2003-10-13",
    "body": "183cm, 86kg",
    "handedness": "우투우타"
  },
  {
    "name": "김상호",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "67",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56467",
    "birthday": "2006-08-19",
    "body": "191cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "박주혁",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "101",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50411",
    "birthday": "2001-05-18",
    "body": "182cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "양현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "19",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "61268",
    "birthday": "1992-08-23",
    "body": "189cm, 104kg",
    "handedness": "우언우타"
  },
  {
    "name": "이재희",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "17",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51460",
    "birthday": "2001-10-11",
    "body": "187cm, 88kg",
    "handedness": "우투좌타"
  },
  {
    "name": "진희성",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "115",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55415",
    "birthday": "2006-05-18",
    "body": "179cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "한수동",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "136",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56436",
    "birthday": "2007-08-13",
    "body": "183cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "허윤동",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "108",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50449",
    "birthday": "2001-06-19",
    "body": "181cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "홍준영",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "112",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55412",
    "birthday": "2004-08-18",
    "body": "180cm, 76kg",
    "handedness": "우투우타"
  },
  {
    "name": "이병헌",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "23",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "69428",
    "birthday": "1999-10-26",
    "body": "180cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "이서준",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "134",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56434",
    "birthday": "2007-06-25",
    "body": "185cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "차동영",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "106",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52400",
    "birthday": "2002-11-01",
    "body": "181cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "강민성",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "127",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55427",
    "birthday": "2006-02-22",
    "body": "183cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "김영웅",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "30",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52430",
    "birthday": "2003-08-24",
    "body": "183cm, 81kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김재상",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "14",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53400",
    "birthday": "2004-07-26",
    "body": "180cm, 81kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이창용",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "50",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "51407",
    "birthday": "1999-06-03",
    "body": "184cm, 89kg",
    "handedness": "우투우타"
  },
  {
    "name": "이한민",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "143",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56443",
    "birthday": "2002-06-04",
    "body": "185cm, 87kg",
    "handedness": "우투우타"
  },
  {
    "name": "조민성",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "132",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52405",
    "birthday": "2003-10-22",
    "body": "181cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "차승준",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "35",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55435",
    "birthday": "2006-11-20",
    "body": "181cm, 88kg",
    "handedness": "우투좌타"
  },
  {
    "name": "강준서",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "105",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53460",
    "birthday": "2000-10-13",
    "body": "183cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "김상민",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "107",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52402",
    "birthday": "2003-12-06",
    "body": "183cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김태훈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 30,
    "jerseyNumber": "25",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "65040",
    "birthday": "1996-03-31",
    "body": "177cm, 78kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이성규",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "13",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "66409",
    "birthday": "1993-08-03",
    "body": "178cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "조세익",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 21,
    "jerseyNumber": "144",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56444",
    "birthday": "2005-10-07",
    "body": "184cm, 83kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "함수호",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "40",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55440",
    "birthday": "2006-03-10",
    "body": "181cm, 88kg",
    "handedness": "좌투좌타"
  }
];
