export default [
  {
    "name": "김건우",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 24,
    "jerseyNumber": "39",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51867",
    "birthday": "2002-07-12",
    "body": "186cm, 88kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김민",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "1",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "68043",
    "birthday": "1999-04-14",
    "body": "185cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "김민준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "40",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56840",
    "birthday": "2006-04-08",
    "body": "183cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "노경은",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 42,
    "jerseyNumber": "38",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "73211",
    "birthday": "1984-03-11",
    "body": "187cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "문승원",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "42",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62869",
    "birthday": "1989-11-28",
    "body": "180cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "박시후",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 25,
    "jerseyNumber": "57",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50812",
    "birthday": "2001-05-10",
    "body": "182cm, 88kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "베니지아노",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 29,
    "jerseyNumber": "41",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56841",
    "birthday": "1997-09-01",
    "body": "198cm, 102kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "서진용",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 34,
    "jerseyNumber": "22",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "61895",
    "birthday": "1992-10-02",
    "body": "184cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "이건욱",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 31,
    "jerseyNumber": "16",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "64861",
    "birthday": "1995-02-13",
    "body": "182cm, 85kg",
    "handedness": "우투우타"
  },
  {
    "name": "이로운",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "92",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53892",
    "birthday": "2004-09-11",
    "body": "185cm, 105kg",
    "handedness": "우투우타"
  },
  {
    "name": "전영준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "28",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "52809",
    "birthday": "2002-04-16",
    "body": "190cm, 100kg",
    "handedness": "우투우타"
  },
  {
    "name": "조병현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "19",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51897",
    "birthday": "2002-05-08",
    "body": "182cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "타케다",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "23",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56823",
    "birthday": "1993-04-03",
    "body": "187cm, 92kg",
    "handedness": "우투우타"
  },
  {
    "name": "해치",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 32,
    "jerseyNumber": "55",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "56855",
    "birthday": "1994-09-29",
    "body": "185cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "신범수",
    "role": "hitter",
    "position": "C",
    "bats": "L",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "25",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "66662",
    "birthday": "1998-01-25",
    "body": "177cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "조형우",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "20",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51865",
    "birthday": "2002-04-04",
    "body": "187cm, 95kg",
    "handedness": "우투우타"
  },
  {
    "name": "고명준",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 24,
    "jerseyNumber": "18",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "51868",
    "birthday": "2002-07-08",
    "body": "185cm, 94kg",
    "handedness": "우투우타"
  },
  {
    "name": "김민준",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "5",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53893",
    "birthday": "2004-03-20",
    "body": "181cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "박성한",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 28,
    "jerseyNumber": "2",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "67893",
    "birthday": "1998-03-30",
    "body": "180cm, 77kg",
    "handedness": "우투좌타"
  },
  {
    "name": "전의산",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 26,
    "jerseyNumber": "47",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50820",
    "birthday": "2000-11-25",
    "body": "188cm, 108kg",
    "handedness": "우투좌타"
  },
  {
    "name": "정준재",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "3",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "54812",
    "birthday": "2003-01-03",
    "body": "165cm, 68kg",
    "handedness": "우투좌타"
  },
  {
    "name": "최정",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 39,
    "jerseyNumber": "14",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "75847",
    "birthday": "1987-02-28",
    "body": "180cm, 90kg",
    "handedness": "우투우타"
  },
  {
    "name": "홍대인",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "97",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "55897",
    "birthday": "2001-11-23",
    "body": "174cm, 76kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김성욱",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 33,
    "jerseyNumber": "31",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "62934",
    "birthday": "1993-05-01",
    "body": "181cm, 83kg",
    "handedness": "우투우타"
  },
  {
    "name": "김재환",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 38,
    "jerseyNumber": "32",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "78224",
    "birthday": "1988-09-22",
    "body": "184cm, 98kg",
    "handedness": "우투좌타"
  },
  {
    "name": "에레디아",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "L",
    "age": 35,
    "jerseyNumber": "27",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "53827",
    "birthday": "1991-01-31",
    "body": "178cm, 88kg",
    "handedness": "좌투우타"
  },
  {
    "name": "오태곤",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 35,
    "jerseyNumber": "37",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "60558",
    "birthday": "1991-11-18",
    "body": "186cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "최지훈",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "54",
    "status": "active",
    "source": "KBO 등록현황",
    "playerId": "50854",
    "birthday": "1997-07-23",
    "body": "178cm, 82kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김현재",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "09",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55895",
    "birthday": "2006-07-03",
    "body": "174cm, 78kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "류현곤",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "104",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53806",
    "birthday": "2004-11-10",
    "body": "178cm, 78kg",
    "handedness": "우투우타"
  },
  {
    "name": "윤태현",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "12",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52867",
    "birthday": "2003-10-10",
    "body": "189cm, 93kg",
    "handedness": "우언우타"
  },
  {
    "name": "정동윤",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 29,
    "jerseyNumber": "51",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "66858",
    "birthday": "1997-10-22",
    "body": "193cm, 103kg",
    "handedness": "우투좌타"
  },
  {
    "name": "최용준",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "R",
    "age": 25,
    "jerseyNumber": "67",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "50650",
    "birthday": "2001-12-19",
    "body": "192cm, 105kg",
    "handedness": "우투우타"
  },
  {
    "name": "한두솔",
    "role": "pitcher",
    "position": "P",
    "bats": "",
    "throws": "L",
    "age": 29,
    "jerseyNumber": "34",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68092",
    "birthday": "1997-01-15",
    "body": "177cm, 86kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "김민식",
    "role": "hitter",
    "position": "C",
    "bats": "L",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "24",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "62864",
    "birthday": "1989-06-28",
    "body": "180cm, 80kg",
    "handedness": "우투좌타"
  },
  {
    "name": "이지영",
    "role": "hitter",
    "position": "C",
    "bats": "R",
    "throws": "R",
    "age": 40,
    "jerseyNumber": "56",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "79456",
    "birthday": "1986-02-27",
    "body": "177cm, 88kg",
    "handedness": "우투우타"
  },
  {
    "name": "김요셉",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 19,
    "jerseyNumber": "46",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56846",
    "birthday": "2007-05-03",
    "body": "188cm, 81kg",
    "handedness": "우투좌타"
  },
  {
    "name": "김태윤",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "36",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52803",
    "birthday": "2003-02-28",
    "body": "170cm, 65kg",
    "handedness": "우투좌타"
  },
  {
    "name": "석정우",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "52",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "52804",
    "birthday": "1999-01-20",
    "body": "180cm, 82kg",
    "handedness": "우투우타"
  },
  {
    "name": "안재연",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 23,
    "jerseyNumber": "111",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56811",
    "birthday": "2003-04-10",
    "body": "177cm, 83kg",
    "handedness": "우투좌타"
  },
  {
    "name": "장현진",
    "role": "hitter",
    "position": "IF",
    "bats": "L",
    "throws": "R",
    "age": 22,
    "jerseyNumber": "05",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55899",
    "birthday": "2004-05-18",
    "body": "180cm, 86kg",
    "handedness": "우투좌타"
  },
  {
    "name": "최윤석",
    "role": "hitter",
    "position": "IF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "65",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55894",
    "birthday": "2006-04-25",
    "body": "187cm, 93kg",
    "handedness": "우투우타"
  },
  {
    "name": "김정민",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 22,
    "jerseyNumber": "48",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "53865",
    "birthday": "2004-03-07",
    "body": "180cm, 75kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이승민",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 21,
    "jerseyNumber": "9",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "54806",
    "birthday": "2005-01-06",
    "body": "187cm, 90kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "이승빈",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "R",
    "age": 20,
    "jerseyNumber": "106",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "56806",
    "birthday": "2006-11-24",
    "body": "180cm, 79kg",
    "handedness": "우투우타"
  },
  {
    "name": "이원준",
    "role": "hitter",
    "position": "OF",
    "bats": "R",
    "throws": "L",
    "age": 20,
    "jerseyNumber": "100",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "55893",
    "birthday": "2006-03-15",
    "body": "181cm, 95kg",
    "handedness": "좌투우타"
  },
  {
    "name": "이정범",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "L",
    "age": 28,
    "jerseyNumber": "33",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "67807",
    "birthday": "1998-04-10",
    "body": "178cm, 88kg",
    "handedness": "좌투좌타"
  },
  {
    "name": "최준우",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 27,
    "jerseyNumber": "7",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "68868",
    "birthday": "1999-03-25",
    "body": "175cm, 78kg",
    "handedness": "우투좌타"
  },
  {
    "name": "한유섬",
    "role": "hitter",
    "position": "OF",
    "bats": "L",
    "throws": "R",
    "age": 37,
    "jerseyNumber": "35",
    "status": "futures",
    "source": "KBO 퓨처스 등록현황",
    "playerId": "62895",
    "birthday": "1989-08-09",
    "body": "190cm, 105kg",
    "handedness": "우투좌타"
  }
];
